In [1]:
import numpy as np


1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

In [3]:
a_bidimensional = np.random.randint(34, 98, (4,3))
a_bidimensional

array([[56, 95, 97],
       [83, 57, 51],
       [36, 97, 38],
       [91, 57, 64]])

In [4]:
a_bidimensional.ndim

2

In [5]:
a_bidimensional.dtype

dtype('int64')

2. Crea tres *arrays* (unidimensional, bidimensional y multidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    lista3 = [[[1,2,3],[1,2,3],[1,2,3]]]
    ```

    **Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido

In [6]:
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]
lista3 = [[[1,2,3],[1,2,3],[1,2,3]]]

In [7]:
a1 = np.array(lista1)
a2 = np.array(lista2)
a3 = np.array(lista3)

def caracteristicas_array(array):
    print("Las dimensiones del array son:")
    print(array.ndim)
    print("------------------")
    
    print("El tipo de datos del array es:")
    print(array.dtype)
    print("------------------")
    
    print("La forma del array es:")
    print(array.shape)
    print("------------------")
    
    print("El tamaño del array es:")
    print(array.size)
    print("------------------")

In [8]:
caracteristicas_array(a1)

Las dimensiones del array son:
1
------------------
El tipo de datos del array es:
int64
------------------
La forma del array es:
(5,)
------------------
El tamaño del array es:
5
------------------


In [9]:
caracteristicas_array(a2)

Las dimensiones del array son:
2
------------------
El tipo de datos del array es:
int64
------------------
La forma del array es:
(2, 4)
------------------
El tamaño del array es:
8
------------------


In [10]:
caracteristicas_array(a3)

Las dimensiones del array son:
3
------------------
El tipo de datos del array es:
int64
------------------
La forma del array es:
(1, 3, 3)
------------------
El tamaño del array es:
9
------------------


3. Crea un *array* de todo 0 con tres dimensiones

    Explica el array:
    - ¿Cuántas dimensiones hay? 
    - ¿Qué tamaño tiene?
    - ¿Qué forma tiene?


In [14]:
a_ceros_tri = np.zeros((2,3,4))
a_ceros_tri

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
caracteristicas_array(a_ceros_tri)

Las dimensiones del array son:
3
------------------
El tipo de datos del array es:
float64
------------------
La forma del array es:
(2, 3, 4)
------------------
El tamaño del array es:
24
------------------


4. Crea un *array* vacío de 2 x 5 X 4. 

    - ¿Qué valores nos han salido en el *array*?  

    - ¿Por qué nos salen esos valores? 

In [16]:
a_vacio = np.empty((2,5,4))
a_vacio

array([[[ 1.61132910e-316,  0.00000000e+000,  1.38338381e-321,
         -1.15293361e+277],
        [ 1.63352819e-301,  3.82599592e-297,  7.46699287e-301,
          2.50789587e-292],
        [ 1.86989321e-306,  1.07691062e-282,  1.34047036e-272,
          1.63380945e-301],
        [ 2.10053204e-301,  4.39683727e-003,  7.93544652e-301,
          1.63358159e-301],
        [ 2.38303345e-022,  1.63380946e-301,  5.01872752e-292,
          3.02950552e-268]],

       [[ 2.15384422e-282,  2.76059428e+055,  2.49431817e-306,
          5.21013085e-296],
        [ 3.29099727e-287,  9.53817931e-292,  2.38974292e-253,
          2.58046964e-263],
        [ 7.02484925e-292,  1.56528437e-248,  3.50048627e-301,
          5.57567129e-309],
        [ 4.54292274e-268,  1.39863855e-309,  1.39255974e-309,
          1.69239896e-258],
        [ 1.75106013e-253, -2.34223104e-258,  4.23936054e-307,
          0.00000000e+000]]])

5. En este ejercicio vamos a crear dos *arrays*:

    - Un *array* tridimensional 5x2x3 con todos los valores iguales a 1.


    - Un *array* tridimensional de 2 x 3 x 5  con números aleatorios entre 0-1


In [18]:
a_tri_unos = np.ones((5,2,3))
a_tri_unos

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
a_tri_ale = np.random.rand(2,3,5)
a_tri_ale

array([[[0.51418843, 0.70350504, 0.64807499, 0.78578542, 0.25395666],
        [0.95544974, 0.42440717, 0.44693008, 0.19023966, 0.51637087],
        [0.18441315, 0.5411937 , 0.09170949, 0.4796999 , 0.47114777]],

       [[0.25630478, 0.91128477, 0.68363928, 0.14030859, 0.88196085],
        [0.30662656, 0.54056464, 0.44800661, 0.61797851, 0.11481143],
        [0.23662257, 0.87235313, 0.99467557, 0.78567244, 0.83913159]]])

In [21]:
# no se pueden sumar dos arrays que no tienen la misma forma
a_tri_ale + a_tri_unos

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


6. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8(incluido). 

In [26]:
array_unidimensional = np.random.randint(23, 48, 50)
array_unidimensional

array([38, 38, 41, 36, 43, 42, 29, 27, 23, 26, 42, 37, 26, 30, 45, 47, 32,
       45, 34, 36, 29, 36, 33, 36, 42, 29, 46, 42, 46, 46, 24, 31, 38, 40,
       34, 43, 33, 27, 28, 39, 27, 45, 37, 43, 24, 41, 37, 37, 35, 23])

In [27]:
array_unidimensional[0]

38

In [28]:
array_unidimensional[1::2]

array([38, 36, 42, 27, 26, 37, 30, 47, 45, 36, 36, 36, 29, 42, 46, 31, 40,
       43, 27, 39, 45, 43, 41, 37, 23])

In [29]:
array_unidimensional[:4]

array([38, 38, 41, 36])

In [30]:
array_unidimensional[-3:]

array([37, 35, 23])

In [31]:
array_unidimensional[4:9]

array([43, 42, 29, 27, 23])

7. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.

In [33]:
array_bidimensional = np.random.rand(4,5)
array_bidimensional

array([[0.34267521, 0.72624573, 0.50154018, 0.16906269, 0.16310006],
       [0.23393519, 0.51016452, 0.26061622, 0.89611104, 0.17569813],
       [0.79928404, 0.77261508, 0.00184417, 0.14288465, 0.6760445 ],
       [0.98946371, 0.36458507, 0.61968034, 0.21600677, 0.57748753]])

In [35]:
array_bidimensional[0]

array([0.34267521, 0.72624573, 0.50154018, 0.16906269, 0.16310006])

In [36]:
array_bidimensional[::2, :]

array([[0.34267521, 0.72624573, 0.50154018, 0.16906269, 0.16310006],
       [0.79928404, 0.77261508, 0.00184417, 0.14288465, 0.6760445 ]])

In [37]:
array_bidimensional[:, 0]

array([0.34267521, 0.23393519, 0.79928404, 0.98946371])

8. Crea una matriz multidimensional de 2 x 3 x 5 de unos y haz una copia de la matriz multidimensional. 


    - Reemplaza los siguientes valores:

        - Array 1, fila 2, columna 3 por 100
        
        - Array 2, fila 1, columna 4 por 100
        
        - Array 1, fila 3, columna 2 por 100
        
        - Array 2, fila 2, columna 1 por 100

In [41]:
array_1 = np.ones((2,3,5))
array_1_copia = array_1.copy()
array_1_copia

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [44]:
array_1_copia[0, 1, 2] = 100
array_1_copia[1, 0, 3] = 100
array_1_copia[0, 2, 1] = 100
array_1_copia[1, 1, 0] = 100

In [46]:
array_final = array_1_copia.copy()
array_final

array([[[  1.,   1.,   1.,   1.,   1.],
        [  1.,   1., 100.,   1.,   1.],
        [  1., 100.,   1.,   1.,   1.]],

       [[  1.,   1.,   1., 100.,   1.],
        [100.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.]]])

In [48]:
array_unos = np.ones((5,2,3))

array_unos

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [49]:
2,3,5
5,2,3

array_unos = np.transpose(array_unos, (1,2, 0))
array_unos

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [50]:
array_unos + array_final

array([[[  2.,   2.,   2.,   2.,   2.],
        [  2.,   2., 101.,   2.,   2.],
        [  2., 101.,   2.,   2.,   2.]],

       [[  2.,   2.,   2., 101.,   2.],
        [101.,   2.,   2.,   2.,   2.],
        [  2.,   2.,   2.,   2.,   2.]]])

9. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional o multidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

    📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos. 
    

In [51]:
array_100 = np.random.randint(0, 100, (2,3))
array_100

array([[12, 74, 14],
       [ 5, 24, 47]])

In [52]:
def estadisticos(array):
    print("La media es:")
    print(array.mean())
    print("---------------------")
    
    print("La media de las columnas es es:")
    print(np.round(array.mean(axis = 0), 2))
    print("---------------------")
    
    print("El valor máximo de cada fila es:")
    print(array.max(axis = 1))
    print("---------------------")
    
    print("El valor mínimo de cada columna es:")
    print(array.max(axis = 0))
    print("---------------------")
    
    print("¿Hay algun valor mayor que 90? ")
    print(np.any(array > 90))
    print("---------------------")
    
    print("¿Donde están los valores mayores de 90? ")
    print(np.where(array > 90))
    print("---------------------")
    
    print("array ordenado de mayor a menor ")
    print(np.short(array))
    print("---------------------")
    
    
    
    
    

In [53]:
estadisticos(array_100)

La media es:
29.333333333333332
---------------------
La media de las columnas es es:
[ 8.5 49.  30.5]
---------------------
El valor máximo de cada fila es:
[74 47]
---------------------
El valor mínimo de cada columna es:
[12 74 47]
---------------------
¿Hay algun valor mayor que 90? 
False
---------------------
¿Donde están los valores mayores de 90? 
(array([], dtype=int64), array([], dtype=int64))
---------------------
array ordenado de mayor a menor 
[[12 74 14]
 [ 5 24 47]]
---------------------
